name = "docker-image"
account_id = "5016a2189c17a6141641fdd988b98008"
main = "src/index.ts"
workers_dev = true
compatibility_date = "2024-06-08"

kv_namespaces = [
	 { binding = "HAMMAL_CACHE", id = "edf986c7989b4a9abc95cc00b48abe75" }
]
